#!/usr/bin/env bash
rm -f tags
/usr/local/bin/ctags --exclude=.git --exclude=vendor/assets/bower_components --exclude=cache --exclude=doc --exclude=gems --exclude=node_modules --exclude=tmp --recurse --tag-relative
