#!/usr/bin/env sh

SESSION="$1"

cd "$DOTFILES"

tmux new-session -s "$SESSION" -n editor -d
tmux new-window -n shell -t "$SESSION"

tmux send-keys -t "$SESSION":1 'e' C-m ':CtrlP' C-m

tmux select-window -t "$SESSION":1
