#!/usr/bin/env sh

SESSION="$1"

tmux new-session -s "$SESSION" -n editor -d
tmux new-window -n shell -t "$SESSION"
tmux new-window -n server -t "$SESSION"

tmux send-keys -t "$SESSION":1 'e' C-m ':CtrlP' C-m
tmux send-keys -t "$SESSION":3 'cd src' C-m 'nanoc autocompile -p 3002 -H thin' C-m

tmux select-window -t "$SESSION":1
