#!/usr/bin/env sh

SESSION="$1"

tmux new-session -s "$SESSION" -n vim -d
tmux new-window -n shell -t "$SESSION"
tmux new-window -n console -t "$SESSION"
tmux new-window -n tests -t "$SESSION"
tmux new-window -n server -t "$SESSION"
tmux new-window -n logs -t "$SESSION"

tmux send-keys -t "$SESSION":1 'vim' C-m #':CtrlP' C-m
tmux send-keys -t "$SESSION":2 'git pull' C-m 'bundle install' C-m 'bundle exec rake db:migrate' C-m 'fliptable' C-m
tmux send-keys -t "$SESSION":3 'bundle exec foreman run bundle exec rails console' C-m
tmux send-keys -t "$SESSION":5 'bundle exec foreman start' C-m
tmux send-keys -t "$SESSION":6 'tail -f log/development.log' C-m

tmux select-window -t "$SESSION":1
