#!/usr/bin/env bash

_mx () {
  local word=${COMP_WORDS[COMP_CWORD]}
  COMPREPLY=( $(compgen -W "$(ls -l $projects | grep '^d' | awk '{printf $NF" "}')" -- $word) )
}

complete -F _mx mx
#complete -C compgen -W "$(ls -l $projects | grep '^d' | awk '{printf $NF" "}')" -- $word mx
