#!/bin/sh
OUTPUT=$(pmset -g batt | grep Internal | awk '{print $3}' | sed 's/;//')

# Output while unplugged
# Now drawing from 'Battery Power'
#  -InternalBattery-0     55%; discharging; 3:41 remaining present: true

printf "%s" "$OUTPUT"
printf "\n"
