install caskroom/cask/brew-cask
install gawk
install gh
install imagemagick
install jq
install macvim --override-system-vim
install openssl
install the_silver_searcher
install tmux
install wget
install youtube-dl

update
