#!/usr/bin/env bash

ln -fs "$PWD"/bin ~/bin

mkdir -p ~/.config

# base16-shell
git clone https://github.com/chriskempson/base16-shell.git ~/.config/base16-shell

# asdf
git clone https://github.com/asdf-vm/asdf.git ~/.asdf

# shellcheck source=/dev/null
source "$HOME"/.asdf/asdf.sh

asdf plugin-add golang
asdf plugin-add nodejs
asdf plugin-add python
asdf plugin-add ruby
asdf plugin-add rust

expor GNUPGHOME="${ASDF_DIR:-$HOME/.asdf}/keyrings/nodejs" && mkdir -p "$GNUPGHOME" && chmod 0700 "$GNUPGHOME"
bash ~/.asdf/plugins/nodejs/bin/import-release-team-keyring

cd "$HOME" || exit
asdf install
cd - || exit

echo "Installing hub"
go get github.com/github/hub
# shellcheck source=/dev/null
cd "$GOPATH"/src/github.com/github/hub || exit
make install prefix=/usr/local
cd - || exit

echo "Installing vim plugins"
asdf reshim python
pip install --upgrade neovim
nvim -E +PlugUpgrade +PlugUpdate +PlugClean! +qa

# find generic installers and run them interactively
echo "Running generic installers"
find . -name all.sh | while read installer ; do sh -c "${installer}" > /dev/null ; done
