#!/usr/bin/env bash

ln -fs "$PWD"/bin ~/bin

source $HOME/.asdf/asdf.sh

asdf plugin-add golang
asdf plugin-add nodejs
asdf plugin-add python
asdf plugin-add ruby
asdf plugin-add rust

export GNUPGHOME="${ASDF_DIR:-$HOME/.asdf}/keyrings/nodejs" && mkdir -p "$GNUPGHOME" && chmod 0700 "$GNUPGHOME"
bash ~/.asdf/plugins/nodejs/bin/import-release-team-keyring

cd ~/
asdf install
cd -

echo "Installing hub"
go get github.com/github/hub/...

echo "Installing vim plugins"
nvim -E +PlugUpgrade +PlugUpdate +PlugClean! +qa

# find generic installers and run them interactively
echo "Running generic installers"
find . -name all.sh | while read installer ; do sh -c "${installer}" > /dev/null ; done
