#!/usr/bin/env bash

RUBY_VERSION='1.9.3-p194'

OS=`uname -s`
KERNEL=`uname -r`

if [[ $KERNEL =~ 'Darwin' ]] ; then
  brew install git hub tmux macvim zsh
elif [[ $KERNEL =~ 'Linux' ]] ; then
  if [[ -f `command -v pacman` ]] ; then
    pacman -Syu gcc git make tmux vim zsh # Arch Linux
  else
    sudo apt-get install gcc git make tmux vim zsh # Debian
  fi
fi

# Initialize and update git submodules
echo "Initializing and updating git submodules..."
cd ~/.dotfiles
git submodule init
git submodule update

# Download ruby-build
if [ ! -d "$HOME/.rbenv/plugins/ruby-build" ]; then
  echo "Downloading ruby-build..."
  mkdir -p ruby/rbenv.symlink/plugins
  git clone https://github.com/sstephenson/ruby-build.git ruby/rbenv.symlink/plugins/ruby-build
fi

# Move symlinks into place
for file in $DOTFILES/**/*.symlink
do
  name=${file##*/} # Strip path
  name=${name//.symlink} # Strip '.symlink'
  ln -s -i "$file" "$HOME/.$name"
done

# Load rbenv
export PATH="$HOME/.rbenv/bin:$PATH"
eval "$(rbenv init -)"


# Install ruby
echo "Installing Ruby $RUBY_VERSION..."
mkdir $HOME/.tmp
export TMP_DIR=$HOME/.tmp
rbenv install $RUBY_VERSION

echo 'Done!'
