#!/usr/bin/env ruby

brews = [
  'bash',
  'chruby',
  'coreutils',
  'fzf',
  'gawk',
  'git',
  'gnupg2',
  'gnupg', # http://stackoverflow.com/a/40066889
  'homebrew/versions/gcc49',
  'hub',
  'jq',
  'keybase',
  'neovim/neovim/neovim',
  'reattach-to-user-namespace',
  'ruby-install',
  'terminal-notifier',
  'the_silver_searcher',
  'tmux',
  'wget',
]

casks = [
  '1password',
  'google-chrome',
  'grandperspective',
  'iterm2',
  'slack',
  'spectacle',
  'tunnelblick',
]

taps = [
  'cask',
  'fonts',
]

INSTALLED_BREWS = `brew list`.split("\n")
INSTALLED_TAPS = `brew tap`.split("\n")
INSTALLED_CASKS = `brew cask list`.split("\n")

system "brew update"

brews.each do |brew|
  if INSTALLED_BREWS.include? brew
    puts "#{brew} already installed"
  else
    puts "Installing #{brew}"
    system "brew install #{brew}"
  end
end

casks.each do |cask|
  if INSTALLED_CASKS.include? cask
    puts "#{cask} already installed"
  else
    puts "Installing cask #{cask}"
    system "brew cask install #{cask}"
  end
end

taps.each do |tap|
  if ! INSTALLED_TAPS.include? "caskroom/#{tap}"
    system "brew tap caskroom/#{tap}"
  end
end

if INSTALLED_TAPS.include? 'caskroom/cask'
  system "brew cask update"
else
  system "brew tap caskroom/cask"
end


system "ln -s /usr/local/bin/gcc-4.9 /usr/local/bin/gcc"
system "/usr/local/opt/fzf/install"
system "echo /usr/local/bin/bash >> /etc/shells"
system "chsh -s /usr/local/bin/bash"
