#!/usr/bin/env bash
set -e

# Install the latest ruby-build
cd ruby/ruby-build/
sudo ./install.sh
cd ../../
ruby-build --definitions

# Initialize and update git submodules
echo "Initializing git submodules"
git submodule --quiet init
echo "Updating git submodules"
git submodule --quiet update

# Install chruby
if [[ -f /usr/local/share/chruby/chruby.sh ]] ; then
  source /usr/local/share/chruby/chruby.sh
else
  echo "Installing chruby"
  wget -O chruby-0.3.1.tar.gz https://github.com/postmodern/chruby/archive/v0.3.1.tar.gz
  tar -xzvf chruby-0.3.1.tar.gz
  rm -f chruby-0.3.1.tar.gz
  cd chruby-0.3.1/
  sudo make install
  cd ../
  rm -rf chruby-0.3.1/
fi

printf " - What Ruby do you want to install? "
read -e ruby_version

mkdir -p $HOME/.tmp

# Check for desired Ruby
if [[ `ls $HOME/.rubies` =~ $ruby_version ]] ; then
  echo "Ruby $ruby_version installed"
else
  echo "Installing Ruby $ruby_version..."
  export TMPDIR=$HOME/.tmp # This is needed for systems with low memory
  ruby-build $ruby_version $HOME/.rubies/$ruby_version
  rm -rf $HOME/.tmp/ruby-build*
  chruby $ruby_version
  gem install bundler
fi

echo 'Done!'
