#!/usr/bin/env ruby

require 'colorize'

brews = [
  'chruby',
  'fzf',
  'gawk',
  'gcc49',
  'hub'
  'jq',
  'neovim/neovim/neovim',
  'reattach-to-user-namespace',
  'ruby-install',
  'the_silver_searcher',
  'tmux',
  'wget',
]

casks = [
  '1password',
  'google-chrome',
  'iterm2',
  'slack',
  'spectacle',
]

INSTALLED_BREWS = `brew list`.split("\n")
CASK_INSTALLED = `brew tap`.split("\n").include? 'caskroom/cask'
INSTALLED_CASKS = `brew cask list`.split("\n")

system "brew update"
brews.each do |brew|
  if INSTALLED_BREWS.include? brew
    puts "#{brew} already installed"
  else
    puts "Installing #{brew}".green
    system "brew install #{brew}"
  end
end

if CASK_INSTALLED
  system "brew cask update"
else
  system "brew tap caskroom/cask"
end
casks.each do |cask|
  if INSTALLED_CASKS.include? cask
    puts "#{cask} already installed"
  else
    puts "Installing cask #{cask}".green
    system "brew cask install #{cask}"
  end
end
