#!/usr/bin/env bash

# If you want git-credential-netrc
# helper=$(sudo find / -name git-credential-netrc)
# sudo chmod 755 $helper
# sudo ln -s $helper /usr/local/bin/git-credential-netrc

sudo apt-get update > /dev/null
cat $HOME/.default-linux-packages | xargs sudo apt-get install -y

# echo "Installing ctop"
# sudo wget https://github.com/bcicen/ctop/releases/download/v0.6.1/ctop-0.6.1-linux-amd64 -O /usr/local/bin/ctop
# sudo chmod +x /usr/local/bin/ctop

echo "Installing linuxbrew"
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
