#!/usr/bin/env bash

# If you want git-credential-netrc
# helper=$(sudo find / -name git-credential-netrc)
# sudo chmod 755 $helper
# sudo ln -s $helper /usr/local/bin/git-credential-netrc

curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list

sudo add-apt-repository ppa:neovim-ppa/stable -y

sudo apt-get update > /dev/null
cat $HOME/.default-linux-packages | xargs sudo apt-get install -y

echo "Installing ctop"
sudo wget https://github.com/bcicen/ctop/releases/download/v0.6.1/ctop-0.6.1-linux-amd64 -O /usr/local/bin/ctop
sudo chmod +x /usr/local/bin/ctop
