#!/usr/bin/env bash

mkdir -p $HOME/.config

# base16-shell
git clone https://github.com/chriskempson/base16-shell.git $HOME/.config/base16-shell

# asdf
git clone https://github.com/asdf-vm/asdf.git $HOME/.asdf

# packer.nvim
git clone --depth 1 https://github.com/wbthomason/packer.nvim ~/.local/share/nvim/site/pack/packer/start/packer.nvim

# shellcheck source=/dev/null
source "$HOME"/.asdf/asdf.sh

asdf plugin-add deno
asdf plugin-add golang
asdf plugin-add nodejs
asdf plugin-add python
asdf plugin-add ruby
asdf plugin-add rust

cd "$HOME" || exit
asdf install
cd - || exit

echo "Installing vim plugins"
nvim -E +PackerUpdate +PackerInstall +PackerClean +qa
