#!/usr/bin/env bash

ln -fs "$PWD"/bin ~/bin

mkdir -p $HOME/.config

# base16-shell
git clone https://github.com/chriskempson/base16-shell.git $HOME/.config/base16-shell

# asdf
git clone https://github.com/asdf-vm/asdf.git $HOME/.asdf

# shellcheck source=/dev/null
source "$HOME"/.asdf/asdf.sh

asdf plugin-add deno
asdf plugin-add golang
asdf plugin-add nodejs
asdf plugin-add python
asdf plugin-add ruby
asdf plugin-add rust

export GNUPGHOME="${ASDF_DIR:-$HOME/.asdf}/keyrings/nodejs" && mkdir -p "$GNUPGHOME" && chmod 0700 "$GNUPGHOME"
bash $HOME/.asdf/plugins/nodejs/bin/import-release-team-keyring

cd "$HOME" || exit
asdf install
cd - || exit

echo "Installing hub"
go get github.com/github/hub
# shellcheck source=/dev/null
cd "$GOPATH"/src/github.com/github/hub || exit
make install prefix=/usr/local
cd - || exit

echo "Installing vim plugins"
nvim -E +PlugUpgrade +PlugUpdate +PlugClean! +qa
