#!/usr/bin/env bash

git clone --bare https://github.com/adamyonk/dotfiles.git $HOME/.dotfiles

function d {
   git --git-dir=$HOME/.dotfiles/ --work-tree=$HOME $@
}

mkdir -p .dotfiles-backup

d checkout
if [ $? = 0 ]; then
  echo "Checked out dotfiles.";
  else
    echo "Backing up pre-existing dot files.";
    d checkout 2>&1 | egrep "\s+\." | awk {'print $1'} | xargs -I{} mv {} .dotfiles-backup/{}
fi;

d checkout
d config status.showUntrackedFiles no
