#!/usr/bin/env bash

set -e

platform="unknown"
if [[ "$(uname)" == "Darwin" ]]; then
   platform="macos"
elif [[ "$(expr substr $(uname -s) 1 5)" == "Linux" ]]; then
   platform="linux"
elif [[ "$(expr substr $(uname -s) 1 10)" == "MINGW32_NT" ]]; then
   platform="windows"
fi

SCRIPT_DIR=$(dirname $BASH_SOURCE)
platform_bootstrap="$SCRIPT_DIR/bootstrap-$platform"
if [[ -x "$platform_bootstrap" ]]; then
  echo "Running $platform platform bootstrap"

  $platform_bootstrap
fi
