#!/usr/bin/env bash

# Depends on hub, git-branch-porcelain, git-lita-ship, git-merge-pr, git-new-tag

branch=$(git branch-porcelain)
if [ "$branch" == 'master' ]; then
  echo "Run this from a PR branch."
  return
fi

echo -e "\n > hub ci-status"
if [ "$(hub ci-status)" != 'success' ]; then
  read -n 1 -p "CI Failure. Override? " response
  if [ "$response" != 'y' ]; then
    exit 1
  fi
fi

echo -e "\n > git merge-pr"
status="$(git merge-pr)"
echo "$status"
if ! [[ "$status" =~ "success" ]]; then
  exit 1
fi

echo -e "\n > git checkout master"
git checkout master
if [ $? != 0 ]; then
  echo "Could not checkout master"
  exit 1
fi

echo -e "\n > git push origin :$branch"
git push origin :"$branch"
if [ $? != 0 ]; then
  echo "Could not delete remote branch $branch"
fi

echo -e "\n > git pull"
git pull
if [ $? != 0 ]; then
  echo "Could not pull latest"
  exit 1
fi

echo -e "\n > git branch -d $branch"
git branch -d "$branch"
if [ $? != 0 ]; then
  echo "Could not delete local branch $branch"
fi

echo -e "\n > git new-tag"
git new-tag
if [ $? != 0 ]; then
  echo "Unable to create new tag"
  exit 1
fi
