nmap <silent> ]r <Plug>(coc-diagnostic-next)
nmap <silent> [r <Plug>(coc-diagnostic-prev)
nmap <silent> <leader>dd <Plug>(coc-definition)
nmap <silent> <leader>dr <Plug>(coc-references)
nmap <silent> <leader>di <Plug>(coc-implementation)
vmap <silent> <leader>f <Plug>(coc-format-selected)
nmap <silent> <leader>f <Plug>(coc-format-selected)
nmap <silent> <leader>F <Plug>(coc-format)
