#!/usr/bin/env sh

# inspired by https://gist.github.com/ysugimoto/0f5391314954cba2b45e2d68cbb982be

_npm_run () {
  CURRENT="${COMP_WORDS[COMP_CWORD]}"
  SUBCOMMAND="${COMP_WORDS[COMP_CWORD-1]}"
  if [ "${SUBCOMMAND}" != "run" ]; then
    return
  fi
  DIR="$(pwd)"
  while [ ! -f "${DIR}/package.json" ]; do
    if [ "${DIR}" = "/" ]; then
      return
    fi
    DIR=$(cd "$(dirname "$(readlink "$DIR" || echo "$DIR")")" || exit; pwd)
  done
  SCRIPTS=$(jq --raw-output '.scripts | keys | .[]' < "$DIR/package.json" | grep --invert-match "^=\\+" | tr "\\n" " ")
  COMPREPLY=( $(compgen -W "$SCRIPTS" "$CURRENT") )
}

complete -F _npm_run npm
